M48
; DRILL file {KiCad 8.0.3} date 2024-07-01T21:17:27+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-01T21:17:27+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X114.08Y-55.19
X114.08Y-60.97
X114.095Y-74.31
X114.095Y-80.09
M30
